### ISSUE TITLE
`text` markdown style overrides other text styles.

### ISSUE THREAD

**Issue by alvaromb** [CharlesMangwa/react-native-simple-markdown#37]
If we configure the markdown to have a `text` style prop like this:

```js
{
  text: {
    color: 'black',
  },
  heading1: {
    color: 'red',
    fontSize: 20,
    fontWeight: '500',
    marginBottom: 15,
  },
}
```

The text `color` prop in the `heading1` entry will be overridden. In order to customise the text color of the heading, the `text` entry must be removed.

PS: I know I've opened several bugs, I'll try to send PRs for them as soon as I can.

**Comment by CharlesMangwa** [comment]
Hi @alvaromb! I started working on this issue and had promising results. However, it required a little bit of refactoring but also testing all the rules. Your PRs will be very welcome 💪

**Comment by alizbazar** [comment]
The same issue seems to appear also with other tags, such as link, strong and so on. It seems to be caused by text tag always being at the root of every text, overriding any specific overlapping definitions, such as link or strong.

Essentially this prevents from changing default text color while also using different color for the links. Any ideas how to overcome this?

**Comment by alizbazar** [comment]
This would not be a problem if text wasn't at the "root" of every other textual tag. Or if there was a way to define default text styles for the top most Text tag that then could be overriden by other tags.

**Comment by ido-kang** [comment]
hey!
any news about it?  any fix?

**Comment by CharlesMangwa** [comment]
This would be handle in v2 👍
